// <auto-generated />
using System;
using Linklives.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Linklives.Migrations
{
    [DbContext(typeof(LinklivesContext))]
    [Migration("20220506123213_Move LinkRating.Category to LinkRatingOptions.Category and change type to enum")]
    partial class MoveLinkRatingCategorytoLinkRatingOptionsCategoryandchangetypetoenum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("LifeCourseLink", b =>
                {
                    b.Property<int>("LifeCoursesId")
                        .HasColumnType("int");

                    b.Property<int>("LinksId")
                        .HasColumnType("int");

                    b.HasKey("LifeCoursesId", "LinksId");

                    b.HasIndex("LinksId");

                    b.ToTable("LifeCourseLink");
                });

            modelBuilder.Entity("Linklives.Domain.LifeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data_version")
                        .HasColumnType("text");

                    b.Property<bool>("Is_historic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnType("Varchar(350)");

                    b.Property<int>("Life_course_id")
                        .HasColumnType("int");

                    b.Property<string>("Link_ids")
                        .HasColumnType("text");

                    b.Property<string>("N_sources")
                        .HasColumnType("text");

                    b.Property<string>("Pa_ids")
                        .HasColumnType("text");

                    b.Property<string>("Source_ids")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("LifeCourses");
                });

            modelBuilder.Entity("Linklives.Domain.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data_version")
                        .HasColumnType("text");

                    b.Property<int>("Duplicates")
                        .HasColumnType("int");

                    b.Property<bool>("Is_historic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Iteration")
                        .HasColumnType("text");

                    b.Property<string>("Iteration_inner")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("Varchar(350)");

                    b.Property<string>("Link_id")
                        .HasColumnType("text");

                    b.Property<string>("Method_id")
                        .HasColumnType("text");

                    b.Property<int>("Pa_id1")
                        .HasColumnType("int");

                    b.Property<int>("Pa_id2")
                        .HasColumnType("int");

                    b.Property<string>("Score")
                        .HasColumnType("text");

                    b.Property<int>("Source_id1")
                        .HasColumnType("int");

                    b.Property<int>("Source_id2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Linklives.Domain.LinkRating", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("RatingId");

                    b.HasIndex("User");

                    b.ToTable("LinkRatings");
                });

            modelBuilder.Entity("Linklives.Domain.RatingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Heading")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RatingOptions");
                });

            modelBuilder.Entity("LifeCourseLink", b =>
                {
                    b.HasOne("Linklives.Domain.LifeCourse", null)
                        .WithMany()
                        .HasForeignKey("LifeCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linklives.Domain.Link", null)
                        .WithMany()
                        .HasForeignKey("LinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linklives.Domain.LinkRating", b =>
                {
                    b.HasOne("Linklives.Domain.Link", "Link")
                        .WithMany("Ratings")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linklives.Domain.RatingOption", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Linklives.Domain.Link", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
