//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linklives.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PAStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PAStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linklives.Resources.PAStrings", typeof(PAStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankomst.
        /// </summary>
        public static string arrival {
            get {
                return ResourceManager.GetString("arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankommet.
        /// </summary>
        public static string arrived {
            get {
                return ResourceManager.GetString("arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dåb.
        /// </summary>
        public static string babtism {
            get {
                return ResourceManager.GetString("babtism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dåb.
        /// </summary>
        public static string baptism {
            get {
                return ResourceManager.GetString("baptism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dåbsbarn.
        /// </summary>
        public static string baptized {
            get {
                return ResourceManager.GetString("baptized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begravelse.
        /// </summary>
        public static string burial {
            get {
                return ResourceManager.GetString("burial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begravelse.
        /// </summary>
        public static string burial_protocol {
            get {
                return ResourceManager.GetString("burial_protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folketælling.
        /// </summary>
        public static string census {
            get {
                return ResourceManager.GetString("census", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmand.
        /// </summary>
        public static string confirmand {
            get {
                return ResourceManager.GetString("confirmand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmand.
        /// </summary>
        public static string confirmant {
            get {
                return ResourceManager.GetString("confirmant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afdøde.
        /// </summary>
        public static string deceased {
            get {
                return ResourceManager.GetString("deceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrejse.
        /// </summary>
        public static string departure {
            get {
                return ResourceManager.GetString("departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrejst.
        /// </summary>
        public static string departured {
            get {
                return ResourceManager.GetString("departured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kvinde.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far.
        /// </summary>
        public static string father {
            get {
                return ResourceManager.GetString("father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brudgom.
        /// </summary>
        public static string groom {
            get {
                return ResourceManager.GetString("groom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mand.
        /// </summary>
        public static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielse.
        /// </summary>
        public static string marriage {
            get {
                return ResourceManager.GetString("marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mor.
        /// </summary>
        public static string mother {
            get {
                return ResourceManager.GetString("mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ægtefælle.
        /// </summary>
        public static string spouse {
            get {
                return ResourceManager.GetString("spouse", resourceCulture);
            }
        }
    }
}
