//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linklives.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PAStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PAStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linklives.Resources.PAStrings", typeof(PAStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andet.
        /// </summary>
        public static string andet {
            get {
                return ResourceManager.GetString("andet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barn.
        /// </summary>
        public static string barn {
            get {
                return ResourceManager.GetString("barn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afdød.
        /// </summary>
        public static string deceased {
            get {
                return ResourceManager.GetString("deceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far.
        /// </summary>
        public static string father {
            get {
                return ResourceManager.GetString("father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svigerfar.
        /// </summary>
        public static string fatherinlaw {
            get {
                return ResourceManager.GetString("fatherinlaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hans barn.
        /// </summary>
        public static string hans_barn {
            get {
                return ResourceManager.GetString("hans barn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendes barn.
        /// </summary>
        public static string hendes_barn {
            get {
                return ResourceManager.GetString("hendes barn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husfader.
        /// </summary>
        public static string husfader {
            get {
                return ResourceManager.GetString("husfader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husmoder.
        /// </summary>
        public static string husmoder {
            get {
                return ResourceManager.GetString("husmoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hustru.
        /// </summary>
        public static string kone {
            get {
                return ResourceManager.GetString("kone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mor.
        /// </summary>
        public static string mother {
            get {
                return ResourceManager.GetString("mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svigermor.
        /// </summary>
        public static string motherinlaw {
            get {
                return ResourceManager.GetString("motherinlaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ægtefælle.
        /// </summary>
        public static string spouse {
            get {
                return ResourceManager.GetString("spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string tjeneste {
            get {
                return ResourceManager.GetString("tjeneste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
    }
}
